language: android

sudo: false

android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

before_install:
 - chmod +x gradlew

script:
  - "./gradlew assembleDebug"
    
deploy:
  provider: releases
  api_key: 426c51dc3eb12b7a1240fc699af1e3a175d88216
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
