language: android

sudo: false

android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

script:
  - "./gradlew assembleRelease"
  
before_install:
 - chmod +x gradlew
 
deploy:
  provider: releases
  api_key:
    secure: dNe8wT18YscrzaAW9nsX
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
